version: '3.9'

networks:
  ml_network_app:
    external: true

services:
  nodejs:
    container_name: ml-controller-front-app
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    # environment:
    #   DB_SCHEMA: postgres
    #   DB_USER: postgres
    #   DB_PASSWORD: postgres
    #   DB_HOST: postgres
    volumes:
      - .:/opt/app
    ports:
      - '3001:3001'
    # network_mode: host
    networks:
      ml_network_app:
        aliases:
          - ml_network_app